### ISSUE TITLE
Installation error when installing with vignette

### ISSUE THREAD

**Issue by andersgs** [caitiecollins/treeWAS#1]
Hello.

While running the following:

```devtools::install_github("caitiecollins/treeWAS/pkg", build_vignettes = TRUE)```

I got the following error:

```Quitting from lines 308-318 (treeWAS_vignette.Rmd) 
Error: processing vignette 'treeWAS_vignette.Rmd' failed with diagnostics:
object 'snps.reconstruction' not found```

I have tried installing on Mac and Linux, and got the same error.

Inspecting the code, line 317 has the following piece of code:

```snps.reconstruction <- snps.reconstruction[-which(rownames(snps.reconstruction) %in% toRemove), ]```

But, `snps.reconstruction` is not defined anywhere in the code.

Cheers.

Anders.

**Comment by caitiecollins** [comment]
Hi Anders, 

Thank you for letting me know. Forgot to push a last set of changes. That issue should be resolved now. 

And thank you for flagging the other issues (re: licence etc.). I apologise that I'm not able to get to everything immediately. I'm on holiday at the moment, but I will be back on June 6th, so I'll be able to respond more fully when I return. 

I really appreciate your interest and your helpful comments. 

All the best, 
Caitlin.

**Comment by xiaohai1990** [comment]
Hi, caitiecollins,

I'm interested in your software treeWAS. 

But while running the following:

install_github("caitiecollins/treeWAS/pkg", build_vignettes = TRUE)

I got the following error:

> install_github("caitiecollins/treeWAS/pkg", build_vignettes = TRUE)
Installation failed: An unknown option was passed in to libcurl

Could you please help me?

**Comment by caitiecollins** [comment]
Hi, 

Very happy to hear you're interested in trying out treeWAS! 

I'm sorry it doesn't appear to be installing correctly for you at the moment. 

I haven't seen this particular error before, but if you could provide me with any potentially relevant additional information, that would be very helpful. 
Eg. Operating system, exact lines of code you ran from start to finish, any other packages you had loaded prior to running the install_github line? 

And if you haven't tried it, it would also be useful for me to know if the install_github line works without the vignetttes, as in, what happens if you try only: 

install_github("caitiecollins/treeWAS/pkg", build_vignettes = FALSE)


Thanks very much. 
I'm sure we can get it up and running!

Best, 
Caitlin.
