### ISSUE TITLE
homoplasies

### ISSUE THREAD

**Issue by plasmid02** [caitiecollins/treeWAS#16]
Could you explain a little bit more how the homoplasy scores are calculated ?(asking because I'm interested in looking at homoplasies sidewise across a number of trees).  It looks like the Phangorn Fitch parsimony score is being reported.

thanks!

**Comment by caitiecollins** [comment]
Hi, 

So I think I may need to better understand your question. I'm going to take a stab at answering, but please let me know which parts of this are relevant to your question, and we can go from there. 

Starting with your use of multiple trees in this context: Do you mean trees of different samples or even species? Or multiple trees of the same sample?

In terms of the use of homplasies within treeWAS: You're correct in thinking that we use the Fitch parsimony score to get the homoplasy distribution (defined as a histogram of the number of substitutions per site across the tree). We only have one set of homoplasy scores (the Fitch scores or, optionally, a homoplasy distribution provided to the 'n.subs' argument by the user) during this part of the procedure, and we draw from this homoplasy distribution to simulate the null genetic data. 
Is this the "homoplasy score" you were referring to?
Are you trying to identify a single homoplasy distribution across multiple separate trees? 

The other place "homoplasies" crop up is in the calculation of the association scores (which might also be referred to as "homoplasy scores", at least in the case of our Score 2 and Score 3, which rely on ancestral state reconstruction). 
Is this what you were referring to instead? 

Thanks for the clarification. 
Cheers, 
Caitlin.

**Comment by plasmid02** [comment]
Hi Caitlin - sorry for my vaguely worded question but I think you answered
it!  I was interested in using the treeWAS functions for calculating
homoplasy distributions of SNPs on trees independent of the use of treeWAS
for association testing.  You confirmed what I thought was true, that the
treeWAS calculated homoplasy distribution is actually the Fitch parsimony
scores.  Thanks and congrats on treeWAS!

cheers

Tim

**Comment by caitiecollins** [comment]
Hi Tim, 

In case it's useful, other ways that I have identified homoplasy distributions for use in treeWAS include using ClonalFrameML and using phangorn's pml function, both of which take a ML approach to reconstructing ancestral sites. These also work well and may be worth looking into if you haven't already. 

With respect to treeWAS, the only other consideration is that we run ancestral state reconstruction on the simulated dataset as well, so for a fairer comparison, it makes sense to run the same Fitch function on both the empirical and simulated datasets. 

To be fair, though, in my experience I have not seen massive discrepancies in homoplasy distributions (or treeWAS results) when inputting the output of these approaches to n.subs instead of using Fitch across the board. 

Good luck homoplasy hunting! 

Best, 
Caitlin.
