### ISSUE TITLE
Phylogenetic tree - bootstrap values

### ISSUE THREAD

**Issue by VincentGreffe** [caitiecollins/treeWAS#17]
Hi Caitie, 

As you might remember I used TreeWAS a while back. 
I worked really well, and now I would like to apply it for another analysis. 

However the bootstrap values of this phylogenetic tree is not that great (many ranging from 0-65). 
I haven't run the program yet, but I was wondering if there was any way to correct for nodes with low bootstrap values?
I'm currently also trying to get a more reliable tree with higher bootstrap values, but haven't had any success so far.

Kind regards,

Vincent

**Comment by caitiecollins** [comment]
Hi Vincent, 

Yes, I remember. Glad to hear it worked last time! 

Your current question is a little challenging. There isn't anything implemented in treeWAS to deal with this at the moment. The trouble is all of the ways I can think of integrating bootstrap values (like collapsing nodes etc.) might bias the analysis pretty terribly. Especially because a low bootstrap doesn't really mean that the node in question is absent and no node should be there in its place. 

Any idea why your tree is so, um, not great? When you say "many ranging from 0-65", what proportion is "many"? Are you building the tree from whole genome sequences or some subset of the data? And how related are your samples---are they plucked from an outbreak or something? 

There might be a potentially computationally-intensive Bayesian solution out there, where treeWAS could basically run simulations across a set of possible trees. Something we could consider if you're quite keen on this dataset and you don't need results immediately.
Sorry I don't have a solution for you right off the bat though. 

Cheers, 
Caitlin.

**Comment by VincentGreffe** [comment]
Thanks for the quick reply!
I was already afraid that correcting for bootstrap values wouldn't be so easy. 

The phylogenetic tree is built from a concatenation of all core genes of strains from the same species (obtained by WGS).
The previous dataset was actually a subset of this dataset, where I used 42 of the 74 strains. 
With the 42 strains, I did receive a good phylogenetic tree (using RAxML), where only 5/34 nodes showed bootstrap values. With the current tree, around 1/3 has bootstrap values that are too low (24/71). 

Your suggestion of using a Bayesian method sounds like it would work, but indeed it would be computationally challenging. 
I will focus on improving the phylogenetic tree, since I think the bootstrap values could be improved somehow. 


Kind regards,

Vincent
