### ISSUE TITLE
long vectors no supported yet

### ISSUE THREAD

**Issue by SionBayliss** [caitiecollins/treeWAS#18]
Hi Caitie, 

On running treeWAS with a large dataset of snps from the core genome I encountered this error. 

```
Error in which(snps == TRUE) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:138
Calls: treeWAS -> snp.sim -> replace -> which
Execution halted
Warning message:
system call failed: Cannot allocate memory 
```

It is most likely a memory issue. It might be a problem with Rccp, similar to the issue mentioned here (https://github.com/RcppCore/Rcpp/issues/302). I will run the newer version of treeWAS with memory limits and provide an update when it has run.

Cheers,
Sion

**Comment by caitiecollins** [comment]
Hi Sion, 

Thanks for letting me know about this. It does look like a memory issue. 

Could you let me know the dimensions of your dataset and whether you are running this on the cluster or not? To identify the problem more specifically and see if there is a solution, I'll probably need to be able to recreate this particular issue myself. 

Do let me know if you do get it up and running otherwise. Certainly if not, we will find a solution, though as I said I may need your help to know a little bit more before we can do that. 

Thanks for the heads up.

Cheers, 
Caitlin.
