### ISSUE TITLE
How can I get accurate P.value

### ISSUE THREAD

**Issue by zhaoxvwahaha** [caitiecollins/treeWAS#29]
Hi,

The treeWAS is amazing tool, I use it in my data set now, but I have some questions about the p.value:

(1) I got too many significant markers from treeWAS, I wonder which are the most significant ones, i.e. I need the priority of these markers, but all the p.value=0 in output, so how can I get the accurate p.value rather than 0.
(2) What's the min.p.value means, is it the threshold of bonf corrected p-value?
(3) What's the p.value in out object of treeWAS (eg. $out$terminal$p.vals), they are base p-value or bonf corrected p-value. 
(4) I found that not all markers with 0 p-value (eg. $out$terminal$p.vals) are significant, i.e. the p-value of some markers are 0, but they are not significant.

Looking forward to your help,
Thank you in advance.

**Comment by zhaoxvwahaha** [comment]
I'll appreciate it very much if you could help me about my above questions. @caitiecollins @xavierdidelot

**Comment by xavierdidelot** [comment]
1) You could try increasing the value of n.snps.sim to build a null distribution using more simulated sites and therefore get more precise estimates of the p-values
2) min.p.value is the smallest possible value of p-value. So any value returned as zero should be interpreted as being in fact below min.p.value
3) they are corrected p-values
4) this may be because not all significant sites are printed on screen, but they are still there in the output
