### ISSUE TITLE
Accessing data points not considered significant

### ISSUE THREAD

**Issue by jessg28** [caitiecollins/treeWAS#44]
Hi, I was wondering if it is possible to view results that were not considered significant but clearly sit separately from the bulk of the results and just below the significance line? Attached is an example of two results I am interested in finding out more about. Thanks Jess.
![Uploading Terminal score.png…]()

**Comment by xavierdidelot** [comment]
It is definitely a good idea to look at these loci with good scores, even if they did not quite make it past the p-value, since treeWAS is quite conservative in the way it corrects for all the multiple testing involved in any GWAS.

To do this, you will need to extract information directly out of the object returned by the treeWAS command. For example if you used `out<-treeWAS(...)` then you can use `out$terminal$corr.dat` to return the terminal scores of all the loci.

For more information see (https://github.com/caitiecollins/treeWAS/wiki/4.-Interpreting-Output)
