### ISSUE TITLE
Phenotypes: NAs, continuous vs. discrete reconstructions, continuous vs. rank

### ISSUE THREAD

**Issue by VincentGreffe** [caitiecollins/treeWAS#9]
Hi Caitie, 

I'm really liking the program so far! 
Currently I'm testing the same genotypic data with multiple phenotypes (both continious and binary data). 
Some of the phenotypic datasets however only apply to a subset of the strains used. 
I was wondering if it is possible to have missing data in the factor/vector containing the phenotype (hence leaving out that strain for that specific analysis).
Practically this would make it much easier, because otherwise I would have to adjust both the tree and the snps file every time.

Greetings,

Vincent

**Comment by caitiecollins** [comment]
Hi Vincent, 

Thanks! 

Are you asking this because you very diligently read the documentation that suggests these individuals be removed prior to running the analysis? Because, if I'm being honest, that's more of a suggestion to avoid any potentials errors that might arise when treeWAS removes missing individuals (which it does automatically). 

Incidentally, you might be asking because you got this error: 
Error in snps.rec[edges[,1],]
(or something to that effect)?

If the latter, I'm sorry to ask you to do this again, but I just found that bug when playing with the tree you sent me this morning. So I've pushed a new fix for that now. You'll have to reinstall it, but it should work just fine now.  But yes, I agree that it's easier not to have to remove these individuals yourself. You don't have to. 

Final note, seeing as you're working with both continuous and binary phenotypes: I have tried to implement checks on the arguments (eg. phen.reconstruction = "parsimony" or "ML") to spit out warnings/notes and make changes internally rather than hitting hard errors. What I'm saying is, technically it may be the case that you are supposed to change that phen.reconstruction argument for each new class of phenotype, but in practice I believe if you keep it as phen.reconstruction = "parsimony", it should automatically switch to "ML" if it encounters a continuous (non-binary) phenotype. 

Let me know if you run into any other issues.
Happy to help. 

Best, 
Caitlin.

**Comment by VincentGreffe** [comment]
Indeed I read it in the documentation but tried it out anyway, to see if it would cause any problems. 
As you predicted, it gave that error and is now fixed by the update you made! :-) 
Many thanks!

Concerning the last note: 
I don't fully comprehend why the phen. reconstruction wouldn't work by using parsimony, but I changed my factor containing the phenotype into a non-binary factor. It did set the reconstruction type to ML but gave the following error: 

`Variable is non-binary. Setting reconstruction type to 'ML'
Error in ace(phen, tree, type = method) : 
  "phy" is not rooted AND fully dichotomous.` 

Greetings,

Vincent

**Comment by caitiecollins** [comment]
Hi again, 

OK, so, several lovely new things for you. 

I've implemented a second ML reconstruction pipeline that will work with non-binary trees. 

I also added a new optional argument to treeWAS called phen.type. By default phen.type is NULL, but it will allow you to specify, for any non-binary phenotypes, whether they are handled as "discrete" or "continuous" during the reconstruction of the ancestral states of the phenotype. 

The new defaults will assume (if phen.type is NULL) that anything that is > 25% unique is "continuous", but you can always specify either way. 

Also, for any phenotype that is "discrete", you will have the option to use either "parsimony" or "ML" for the reconstruction. Incidentally, phen.reconstruction will no longer automatically switch to "ML" unless either phen.type is "continuous" or, if phen.type=NULL, the phenotype is > 25% unique. 

The reason I had been holding back on allowing discrete variables and parsimonious/discrete reconstructions of non-binary variables is, first because treeWAS was originally designed with binary and continuous variables in mind, and second that I don't want to give people the impression that the program will work on ALL categorical variables. So please be careful: treeWAS can now handle ordered, numeric discrete/categorical variables, but the phenotype should NOT be a factor whose levels are 1="cows", 2="chickens", 3="pigs", for example. The association scores assume that the numerical information in the phenotype and its reconstruction is meaningful. There may be room in the future to allow nominal categorical variables, but I'm afraid only ordered/interval discrete variables for now. 

Ok, well, I hope this will be useful! 

Please do let me know if there are any bugs that I've overlooked in the new implementations. Happy to make any fixes or offer advice if anything's unclear. 

All the best, 
Caitlin.

**Comment by VincentGreffe** [comment]
Hi Caitie, 

Thank you for the update. It works perfectly! And the new argument will be indeed very useful! 
Sorry for bombarding you will all these question but there are a few things that are still unclear to me: 

Would you recommend the reconstruction of snps and phenotype to be done by parsimony (or ML)? And, in my case, where I have multiple phenotypes, both continious and binary? And why is it necessary to make the phen. reconstruction with ML? 

Are the discrete phenotypes and continuous phenotypes treated any differently (except the fact that by default the reconstruction respectively happens by parsimony and ML)?

Greetings,

Vincent

**Comment by VincentGreffe** [comment]
Thank you for your clear explanation!
So is it correct to say that ranked values (originating from continuous values, like the example in the vignette), should be treated as continuous? 

Is it also possible to ask a question about the handling of my continuous data?
I, for example, have a continuous phenotype with some datapoints at 0 and some between 0,5 and 1 that are somewhat Gaussian distributed.
My original thoughts of handling this data is to split it into 2 datasets: 
- one binary phenotype: indicating if it is zero or not
- one continuous phenotype
For the latter, I have difficulties deciding if I should rank them or not. I would think that ranking them results in equalizing small and big differences between strains, so I distort my data. However it sometimes contains outliers, potentially giving false positives.

Sorry that I'm drifting away from the original question of this topic. Let me know if I should make a new one.

Greetings,

Vincent

**Comment by caitiecollins** [comment]
Hi, 

No problem, I'm glad it made sense! 

Yes, although conceptually I also think of ranks as discrete values, I would treat them as continuous in treeWAS. The reason for this becomes especially clear when the ranks contain ties: I would prefer to have a continuous reconstruction that treats a ranks of 1.5 as halfway between ranks 1 and 2 than a discrete reconstruction that treats all ranks merely as levels without considering the relative value of those levels. 

As for your continuous phenotype, if I were you I would also try running it as both a binary phenotype and a continuous phenotype. 

It can be difficult to decide whether or not to transform a continuous phenotype into ranks, or to determine whether the real values are more important than the relative values (ranks). I would make one countervailing point to your concern about equalizing small/big differences by ranking. In fact because the association scores give weight to the relative differences between phenotypic values, if your dataset contains outliers and you *don't* transform the phenotype by rank, you may actually run the risk of drowning out all of the relative differences occurring around the median of your phenotype. As so much weight may be given to the massive difference between the outlier(s) and the bulk of the data, conceptually, you may compress the smaller-scale relative differences among the bulk of the data into insignificance. Both concerns may be valid. I'm sorry to say that there isn't a definite rule to follow here. 

That said, from a purely practical standpoint, I have a bit of a *post hoc* cheat that at least allows you to determine whether the skewedness of your phenotype (or lack of transformation by rank) has made the results untrustworthy. 

One of the benefits of treeWAS is that it is generally quite good at keeping the false positive rate low. The only conditions in which this may not be true is when you've got an overly-skewed continuous phenotype. Thankfully, you can usually tell when this is the case by looking at the shape of the null distributions (the histogram plotted by default for each association score) for Scores 1 and 3. 

Usually, the null distribution is right-skewed, like this:
![good_right_skewed_null_dist](https://user-images.githubusercontent.com/7629483/29219701-b08a7c08-7eb0-11e7-926a-77640b650331.png)

Not all null distributions need to be as perfectly right-skewed as the one above. However, a flashing warning of an overly-skewed phenotype is a "backward" *left*-skewed null distribution (for Scores 1 and 3), like this one: 
![bad_left_skewed_null_dist](https://user-images.githubusercontent.com/7629483/29219834-1adb1310-7eb1-11e7-9320-f8c3b0ac9d88.png)

You'll notice in the latter case that you get a whole bunch of (false positive) significant findings as well. This is because with the left-skewed null distribution, treeWAS does not have a nice long right tail in which to refine the location of the significance threshold. Instead, the null distribution falls off a cliff at its upper end and so a significance threshold that is even slightly off can result in a tonne of false positives. 

But, false positives or not, if you are ever unsure about whether to transform your continuous phenotype by rank, I'm afraid there's no hard and fast *a priori* rule, but at least you can take a look at the null distributions for Scores 1 and 3 after the fact to check whether you should go back and rank your phenotype instead. 

Hope that helps! 

All the best, 
Caitlin.

**Comment by VincentGreffe** [comment]
Thank you for that handy tip! 
I was already afraid there was no definitive rule to address the problem.
I will just run the continuous data and based on the distribution I will switch to the ranked data or not.
